(()=>{
const $=s=>document.querySelector(s);const screens=['title-screen','quiz-screen','final-intro-screen','final-screen'];
let questions=[],finals=[],quiz=[],qIndex=0,score=0,answered=false,currentFinal=null;
const show=id=>screens.forEach(s=>$('#'+s).classList.toggle('active',s===id));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const norm=s=>String(s??'').trim().normalize('NFKC').replace(/[\s　]+/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validateQuestion(q){return q&&typeof q.question==='string'&&Array.isArray(q.choices)&&q.choices.length>=4&&new Set(q.choices).size===q.choices.length&&q.choices.includes(q.answer)}
function validateFinal(r){return r&&r.playable!==false&&r.venue&&r.winner&&r.second&&r.fourth&&r.fifth&&r.time}
function valueText(v){return Array.isArray(v)?v.join(' ／ '):String(v??'—')}
function prepareQuiz(){const pool=questions.filter(validateQuestion);quiz=shuffle(pool).slice(0,5).map(q=>({...q,choices:shuffle(q.choices)}));qIndex=0;score=0;answered=false;updateMeter();renderQuestion()}
function updateMeter(){$$('.panel-meter i').forEach((el,i)=>el.classList.toggle('on',i<score))}
function $$(s){return document.querySelectorAll(s)}
function renderQuestion(){const q=quiz[qIndex];answered=false;$('#question-count').textContent=`QUESTION ${qIndex+1} / 5`;$('[id=category]').textContent=q.category||'RACE QUIZ';$('#question-text').textContent=q.question;$('#choices').innerHTML='';$('#answer-mark').hidden=true;$('#panel-get').hidden=true;$('#next-btn').hidden=true;
q.choices.forEach(choice=>{const b=document.createElement('button');b.className='choice';b.textContent=choice;b.addEventListener('click',()=>answerQuestion(choice,b));$('#choices').appendChild(b)})}
function answerQuestion(choice,btn){if(answered)return;answered=true;const q=quiz[qIndex],correct=norm(choice)===norm(q.answer);if(correct)score++;updateMeter();$$('.choice').forEach(b=>b.classList.add('disabled'));btn.classList.add(correct?'correct':'wrong');const mark=$('#answer-mark');mark.hidden=false;mark.textContent=correct?'○':'×';mark.className='answer-mark '+(correct?'ok':'ng');if(correct){$('#panel-get').hidden=false;const names=['TIME','4TH / 5TH','3RD','2ND','VENUE'];$('#panel-get-name').textContent=names[score-1]+' PANEL';}$('#next-btn').hidden=false}
function nextQuestion(){if(!answered)return;if(qIndex<4){qIndex++;renderQuestion()}else{$('#earned-summary').textContent=`${score} / 5 PANELS EARNED`;show('final-intro-screen')}}
function renderFinal(){const valid=finals.filter(validateFinal);if(!valid.length)throw new Error('FINAL問題DBに有効なレースがありません。');currentFinal=valid[Math.floor(Math.random()*valid.length)];const openCount=score;
// Opening order is fixed: TIME -> 4/5 -> 3 -> 2 -> VENUE. Display remains a finish-board style listing.
const rows=[['VENUE',currentFinal.venue,5],['2ND',currentFinal.second,4],['3RD',currentFinal.third,3],['4TH / 5TH',`${valueText(currentFinal.fourth)} ／ ${valueText(currentFinal.fifth)}`,2],['TIME',currentFinal.time,1]];
$('#final-board').innerHTML=rows.map(([label,value,need])=>`<div class="board-row ${openCount>=need?'':'closed'}"><div class="board-label">${label}</div><div class="board-value">${esc(value)}</div></div>`).join('');$('#final-answer').value='';$('#final-answer').disabled=false;$('#final-submit').disabled=false;$('#final-result').hidden=true;$('#restart-btn').hidden=true}
function submitFinal(){const a=norm($('#final-answer').value);if(!a||!currentFinal)return;const ok=a===norm(currentFinal.winner);$('#final-answer').disabled=true;$('#final-submit').disabled=true;const r=$('#final-result');r.hidden=false;r.className='final-result '+(ok?'ok':'ng');r.textContent=ok?'○  CONGRATULATIONS':'×  TRY AGAIN';$('#restart-btn').hidden=false}
async function loadData(){const [qr,fr]=await Promise.all([fetch('questions.json',{cache:'no-store'}),fetch('final_races.json',{cache:'no-store'})]);if(!qr.ok||!fr.ok)throw new Error('問題DBを読み込めませんでした。');questions=await qr.json();finals=await fr.json();questions=Array.isArray(questions)?questions:(questions.questions||[]);finals=Array.isArray(finals)?finals:(finals.races||finals.finalRaces||[]);questions=questions.filter(validateQuestion);finals=finals.filter(validateFinal);if(questions.length<5)throw new Error('通常問題が5問未満です。');if(!finals.length)throw new Error('FINAL問題がありません。');console.info(`Loaded ${questions.length} normal questions / ${finals.length} final races`) }
$('#start-btn').addEventListener('click',()=>{try{prepareQuiz();show('quiz-screen')}catch(e){alert(e.message)}});$('#next-btn').addEventListener('click',nextQuestion);$('#final-start-btn').addEventListener('click',()=>{try{renderFinal();show('final-screen')}catch(e){alert(e.message)}});$('#final-submit').addEventListener('click',submitFinal);$('#final-answer').addEventListener('keydown',e=>{if(e.key==='Enter')submitFinal()});$('#restart-btn').addEventListener('click',()=>show('title-screen'));loadData().catch(e=>{console.error(e);alert('データ読み込みエラー：'+e.message)});
})();
